#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
	/config/ssl

# copy
if [[ ! -e /config/aria2.conf ]]
then
  cp /aria2/conf/aria2.conf.default /config/aria2.conf
fi

if [[ ! -e /config/aria2.session ]]
then
  touch /config/aria2.session
fi

if [[ ! -e /config/dht.dat ]]
then
  touch /config/dht.dat
fi

# permissions
chown -R abc:abc \
	/config \
  /downloads

chmod a+x /aria2/script/delete.sh delete.aria2.sh tracker.sh

# auto updatetracker
if [ $UpdateTracker -eq true ]
then
  bash /aria2/script/tracker.sh
fi
