#!/usr/bin/with-contenv bash

ARIA2_CONF="/config/aria2.conf"

ENSURE_ARIA2_CONF_KEY() {
  local key="$1"
  if ! grep -q "^${key}=" "${ARIA2_CONF}"; then
    if [ -s "${ARIA2_CONF}" ] && [ -n "$(tail -c 1 "${ARIA2_CONF}")" ]; then
      echo >>"${ARIA2_CONF}"
    fi
    echo "${key}=" >>"${ARIA2_CONF}"
  fi
}

SET_ARIA2_CONF_VALUE() {
  local key="$1"
  local value="$2"
  ENSURE_ARIA2_CONF_KEY "${key}"
  sed -i "s@^\(${key}=\).*@\1${value}@" "${ARIA2_CONF}"
}

# extra function
SET_ARIA2_CONF_VALUE "on-download-stop" "/aria2/script/stop.sh"
SET_ARIA2_CONF_VALUE "on-download-complete" "/aria2/script/completed.sh"
SET_ARIA2_CONF_VALUE "on-download-pause" "/aria2/script/pause.sh"
SET_ARIA2_CONF_VALUE "on-download-start" "/aria2/script/start.sh"
# port
SET_ARIA2_CONF_VALUE "rpc-listen-port" "${PORT}"
SET_ARIA2_CONF_VALUE "dht-listen-port" "${BTPORT}"
SET_ARIA2_CONF_VALUE "listen-port" "${BTPORT}"

# bt-save-metadata
if [[ "$SMD" = "true" ]]
then
    SET_ARIA2_CONF_VALUE "bt-save-metadata" "true"
else
    SET_ARIA2_CONF_VALUE "bt-save-metadata" "false"
fi

# file-allocation
if [[ "$FA" = "falloc" ]]
then
    SET_ARIA2_CONF_VALUE "file-allocation" "falloc"
elif [[ "$FA" = "trunc" ]]
then
    SET_ARIA2_CONF_VALUE "file-allocation" "trunc"
elif [[ "$FA" = "prealloc" ]]
then
    SET_ARIA2_CONF_VALUE "file-allocation" "prealloc"
else
    SET_ARIA2_CONF_VALUE "file-allocation" "none"
fi

# auto update tracker
if [ "$UT" == "true" ]
then
  bash /aria2/script/tracker.sh
fi

# rpc update tracker
if [ "$RUT" == "true" ]
then
  cp /aria2/conf/rpc-tracker1 /etc/crontabs/root
  /usr/sbin/crond
else
  cp /aria2/conf/rpc-tracker0 /etc/crontabs/root
fi
