#!/usr/bin/with-contenv bash

# permissions
chown -R abc:abc \
    /config \
    /downloads
  
chmod a+x \
  /aria2/script/delete.sh \
  /aria2/script/recycle.sh \
  /aria2/script/delete.aria2.sh \
  /aria2/script/tracker.sh \
  /aria2/script/move.sh
