#!/usr/bin/with-contenv bash

# permissions
chown -R abc:abc \
    /config \
    /www \
    /downloads

find /aria2/script -name "*.sh" -exec chmod a+x {} \;

# aria2b 重启 cron（仅在 A2B=true 时配置）
[ "${A2B}" = "true" ] && bash /aria2/script/restart-a2b.sh
