#!/usr/bin/with-contenv bash
# shellcheck shell=bash
# 启动 aria2 服务
set -euo pipefail

if [[ -n "${SECRET:-}" ]]; then
	SECRET_TOKEN="--rpc-secret=${SECRET}"
fi

exec \
	s6-setuidgid abc aria2c \
	--conf-path=/config/aria2.conf \
	${SECRET_TOKEN:+"${SECRET_TOKEN}"} \
	--disk-cache="${CACHE:-128M}" \
	--quiet="${QUIET:-true}"
