#!/usr/bin/with-contenv bash

exec \
	s6-setuidgid abc aria2c \
    --conf-path=/config/aria2.conf \
    --rpc-secret=$SECRET \
    --disk-cache=$CACHE \
    --quiet=$QUIET
  > /dev/stdout \
  2 > /dev/stderr

echo 'Exiting aria2'